### ISSUE TITLE
Bundle displays only one binary file

### ISSUE THREAD

**Issue by koffisani** [novaway/NovawayOpenGraphBundle#3]
I just try to install this bundle
```
composer require novaway/open-graph-bundle "^1.0"
```
 with Symfony 2.8 and remarked that I have only one binary file in the folder : 
```
->novaway
  ->open-graph
    ->61f26610db9843fae4899290ddcfa5ea
```
Is this correct ? Is there something wrong ?

**Comment by jdecool** [comment]
Hello @koffisani,

I don't understand your problem.

Could you detail it ?

```
->novaway
  ->open-graph
    ->61f26610db9843fae4899290ddcfa5ea
```

This file structure look like the annotation cache files tree. 
What do you think is wrong with this ?

**Comment by koffisani** [comment]
After the installation, I get this only binary file(`61f26610db9843fae4899290ddcfa5ea`) in the `open-graph` repositry. 

Fortunately, I removed the entry in `composer.json`, run `composer update` and installed it again and it's fixed. Thanks.
